version: '3.8'

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      dockerfile: web/Dockerfile
    container_name: fastapi-web
    ports:
      - "8000:8000"
    depends_on:
      - redis

  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
    depends_on:
      - localstack
      - redis
    deploy:
      replicas: 3
